export const images = {
  logo: require("../assets/images/logo.png"),
  dark_logo: require("../assets/images/dark_logo.png"),
  arrow: require("../assets/images/arrow.png"),
  facebook: require("../assets/images/facebook.png"),
  instagram: require("../assets/images/instagram.png"),
  pinterest: require("../assets/images/pinterest.png"),
  youtube: require("../assets/images/youtube.png"),
  rabbit: require("../assets/images/rabbit.png"),
  woman_buyer: require("../assets/images/woman_buyer.png"),
  man_buyer: require("../assets/images/man_buyer.png"),
  green_rect_item: require("../assets/images/green_rect_item.png"),
  yellow_rect: require("../assets/images/yellow_rect.png"),
  yellow_rect_item: require("../assets/images/yellow_rect_item.png"),
  search: require("../assets/images/search.png"),
  choose: require("../assets/images/choose.png"),
  contact: require("../assets/images/contact.png"),
  white_right_arrow: require("../assets/images/white_right_arrow.png"),
  puppy_with_girl: require("../assets/images/puppy_with_girl.png"),
  puppy_with_woman: require("../assets/images/puppy_with_woman.png"),
  horse_with_woman: require("../assets/images/horse_with_woman.png"),
  puppy: require("../assets/images/puppy.png"),
  horse: require("../assets/images/horse.png"),
  horse_baby: require("../assets/images/horse_baby.png"),
  cat_baby: require("../assets/images/cat_baby.png"),
  goat_baby: require("../assets/images/goat_baby.png"),
  verified_breeders: require("../assets/images/verified_breeders.png"),
  wide_selection: require("../assets/images/wide_selection.png"),
  easy_search: require("../assets/images/easy_search.png"),
} as const;

export default images;
